In [1]:
import pandas as pd

In [4]:
!ls -lh /home/aio/training/data/creditcard-fraud.csv

-rw-r--r-- 1 aio aio 144M Nov  5  2016 /home/aio/training/data/creditcard-fraud.csv

In [5]:
!wc -l /home/aio/training/data/creditcard-fraud.csv

284808 /home/aio/training/data/creditcard-fraud.csv

In [2]:
df = pd.read_csv("/home/aio/training/data/creditcard-fraud.csv")
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
df.Class.value_counts() # 1: fradulent transaction

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
df.Class.value_counts()  /len(df)

Class
0    0.998273
1    0.001727
Name: count, dtype: float64

In [10]:
y = df.Class
X = df.loc[:, "V1":"V28"]
X

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,-0.682920,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,-1.545556,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,-0.577252,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,2.897849,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,-0.256117,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649

In [9]:
n_size = int(0.7 * len(df))
n_size

199364

In [11]:
X_train = X[:n_size]
X_test = X[n_size:]
y_train = y[:n_size]
y_test = y[n_size:]

In [15]:
from sklearn import model_selection, linear_model, pipeline, preprocessing, metrics
import numpy as np


def find_metrics(threshold):

    pipe = pipeline.Pipeline([
        ('scaler', preprocessing.StandardScaler()),
        ('est', linear_model.LogisticRegression()),
    ])

    pipe.fit(X_train, y_train)
    
    
    y_train_prob = pipe.predict_proba(X_train)[:, 1]
    y_test_prob = pipe.predict_proba(X_test)[:, 1]
    y_test_pred = np.where(y_test_prob>threshold, 1, 0)
    y_train_prob = pipe.predict_proba(X_train)[:, 1]
    y_train_pred = np.where(y_train_prob>threshold, 1, 0)
    
    
    pd.DataFrame({"y": y_test, "y_prob": y_test_prob, "y_pred": y_test_pred})
    
    metrics.confusion_matrix(y_test, y_test_pred)

    print("threhsold: ", threshold)
    print("train accuracy: ", metrics.accuracy_score(y_train, y_train_pred))
    print("train precision: ", metrics.precision_score(y_train, y_train_pred))
    print("train recall: ", metrics.recall_score(y_train, y_train_pred))
    print("train f1: ", metrics.f1_score(y_train, y_train_pred))
    
    print("test accuracy: ", metrics.accuracy_score(y_test, y_test_pred))
    print("test precision: ", metrics.precision_score(y_test, y_test_pred))
    print("test recall: ", metrics.recall_score(y_test, y_test_pred))
    print("test f1: ", metrics.f1_score(y_test, y_test_pred))
    print(metrics.confusion_matrix(y_test, y_test_pred))

find_metrics(0.5)

threhsold:  0.5
train accuracy:  0.9990620172147429
train precision:  0.8480565371024735
train recall:  0.625
train f1:  0.719640179910045
test accuracy:  0.999204147794436
test precision:  0.7702702702702703
test recall:  0.5277777777777778
test f1:  0.6263736263736264
[[85318    17]
 [   51    57]]

In [17]:
from sklearn.utils import resample

df_majority = df[df.Class==0]
df_minority = df[df.Class==1]
 
# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,               # sample with replacement
                                 n_samples=len(df_majority), # to match majority class
                                 random_state=123)           # reproducible results
 
# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
df_upsampled.shape

(568630, 31)

In [32]:
from sklearn import model_selection, linear_model, pipeline, preprocessing, metrics
import numpy as np


n_size = int(0.7 * len(df_upsampled))
print("training size: ", n_size)

df_upsampled = df_upsampled.sample(len(df_upsampled)).sort_values("Time")
X = df_upsampled.loc[:, "V1":"V28"]
y = df_upsampled.Class
X_train = X.values[:n_size]
X_test = X.values[n_size:]
y_train = y[:n_size]
y_test = y[n_size:]

def find_metrics(threshold):

    pipe = pipeline.Pipeline([
        ('scaler', preprocessing.StandardScaler()),
        ('est', linear_model.LogisticRegression()),
    ])

    pipe.fit(X_train, y_train)
    
    
    y_train_prob = pipe.predict_proba(X_train)[:, 1]
    y_test_prob = pipe.predict_proba(X_test)[:, 1]
    y_test_pred = np.where(y_test_prob>threshold, 1, 0)
    y_train_prob = pipe.predict_proba(X_train)[:, 1]
    y_train_pred = np.where(y_train_prob>threshold, 1, 0)
    
    
    pd.DataFrame({"y": y_test, "y_prob": y_test_prob, "y_pred": y_test_pred})
    
    metrics.confusion_matrix(y_test, y_test_pred)

    print("threhsold: ", threshold)
    print("train accuracy: ", metrics.accuracy_score(y_train, y_train_pred))
    print("train precision: ", metrics.precision_score(y_train, y_train_pred))
    print("train recall: ", metrics.recall_score(y_train, y_train_pred))
    print("train f1: ", metrics.f1_score(y_train, y_train_pred))
    
    print("test accuracy: ", metrics.accuracy_score(y_test, y_test_pred))
    print("test precision: ", metrics.precision_score(y_test, y_test_pred))
    print("test recall: ", metrics.recall_score(y_test, y_test_pred))
    print("test f1: ", metrics.f1_score(y_test, y_test_pred))
    print(metrics.confusion_matrix(y_test, y_test_pred))

find_metrics(0.5)

training size:  398041
threhsold:  0.5
train accuracy:  0.9540951811496806
train precision:  0.9795441609542429
train recall:  0.933322644080905
train f1:  0.9558749661914145
test accuracy:  0.9373464877571238
test precision:  0.9601267336202773
test recall:  0.889018044946308
test f1:  0.9232051503132724
[[95657  2668]
 [ 8020 64244]]

In [33]:
y.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [34]:
pd.Series(y_train).value_counts()

Class
1    212051
0    185990
Name: count, dtype: int64

In [36]:
pd.Series(y_test).value_counts()/len(y_test)

Class
0    0.576385
1    0.423615
Name: count, dtype: float64