In [1]:
import pandas as pd

In [3]:
movies = pd.read_csv('https://raw.githubusercontent.com/abulbasar/data/master/movielens/movies.csv')
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary
9123,164977,The Gay Desperado (1936),Comedy
9124,164979,"Women of '69, Unboxed",Documentary

1. Load movies.csv and ratings.csv
2. How many records are there in movies and ratings dataframe [movies: 9125, ratings: 100004]
3. Find the movies, for which title contains Godfather? [Hint: use movies.title.str.contains() to find substring in title]
4. How many ratings the movie "Godfather, The (1972)" has received?[Answer: 200]
5. Using ratings dataframe, calculate average rating and number of ratings for each movie. What is the average rating for "Godfather, The (1972)" [Answer: 4.487]
6. Select all movie Ids that have received more than 100 ratings. How many movies are there having more than 100 ratings? [Answer: 149]
7. From the output of step 5 and 6, take top 10 records with highest avg rating. [Hint: use sort and iloc] 
8. Merge the output of 7 with movies dataframe to show title. [Hint: call pd.merge function]
9. Find top 3 genres by the number of movies. [Answer: 'Drama', 'Comedy', 'Thriller']
10. For each genre find top 3 movies

In [8]:
ratings = pd.read_csv('https://raw.githubusercontent.com/abulbasar/data/master/movielens/ratings.csv')
ratings

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [9]:
ratings.shape

(100004, 4)

In [10]:
movies.shape

(9125, 3)

In [11]:
movies[movies.title.str.contains('Godfather')]

      movieId                            title                        genres
695       858            Godfather, The (1972)                   Crime|Drama
977      1221   Godfather: Part II, The (1974)                   Crime|Drama
1585     2023  Godfather: Part III, The (1990)  Crime|Drama|Mystery|Thriller
5470     8607          Tokyo Godfathers (2003)     Adventure|Animation|Drama

In [16]:
m = movies[movies.title == 'Godfather, The (1972)'].movieId.tolist()[0]
m

858

In [22]:
avg_ratings = ratings.groupby("movieId").rating.agg(["count", "mean"]).query('count>100')
avg_ratings

         count      mean
movieId
1          247  3.872470
2          107  3.401869
6          104  3.884615
10         122  3.450820
25         101  3.742574
...        ...       ...
7438       103  3.665049
8961       126  3.861111
33794      105  3.857143
58559      121  4.235537
79132      111  4.049550

[149 rows x 2 columns]

In [25]:
top10 = avg_ratings.sort_values("mean", ascending=False).head(10)
top10

         count      mean
movieId
858        200  4.487500
318        311  4.487138
1221       135  4.385185
50         201  4.370647
527        244  4.303279
1193       144  4.256944
608        224  4.256696
296        324  4.256173
2858       220  4.236364
58559      121  4.235537

In [26]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [27]:
top10.merge(movies, left_index=True, right_on="movieId")

,count,mean,movieId,title,genres
695,200,4.487500,858,"Godfather, The (1972)",Crime|Drama
284,311,4.487138,318,"Shawshank Redemption, The (1994)",Crime|Drama
977,135,4.385185,1221,"Godfather: Part II, The (1974)",Crime|Drama
48,201,4.370647,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
472,244,4.303279,527,Schindler's List (1993),Drama|War
951,144,4.256944,1193,One Flew Over the Cuckoo's Nest (1975),Drama
535,224,4.256696,608,Fargo (1996),Comedy|Crime|Drama|Thriller
266,324,4.256173,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
2288,220,4.236364,2858,American Beauty (1999),Drama|Romance
6916,121,4.235537,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX

In [31]:
movies['genres'] = movies.genres.str.split("|")
movies

,movieId,title,genres
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]
...,...,...,...
9120,162672,Mohenjo Daro (2016),"[Adventure, Drama, Romance]"
9121,163056,Shin Godzilla (2016),"[Action, Adventure, Fantasy, Sci-Fi]"
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,[Documentary]
9123,164977,The Gay Desperado (1936),[Comedy]
9124,164979,"Women of '69, Unboxed",[Documentary]

In [32]:
movies.explode("genres")

      movieId                                              title       genres
0           1                                   Toy Story (1995)    Adventure
0           1                                   Toy Story (1995)    Animation
0           1                                   Toy Story (1995)     Children
0           1                                   Toy Story (1995)       Comedy
0           1                                   Toy Story (1995)      Fantasy
...       ...                                                ...          ...
9121   163056                               Shin Godzilla (2016)      Fantasy
9121   163056                               Shin Godzilla (2016)       Sci-Fi
9122   163949  The Beatles: Eight Days a Week - The Touring Y...  Documentary
9123   164977                           The Gay Desperado (1936)       Comedy
9124   164979                              Women of '69, Unboxed  Documentary

[20340 rows x 3 columns]

In [33]:
movies.explode("genres").genres.value_counts()

genres
Drama                 4365
Comedy                3315
Thriller              1729
Romance               1545
Action                1545
Adventure             1117
Crime                 1100
Horror                 877
Sci-Fi                 792
Fantasy                654
Children               583
Mystery                543
Documentary            495
Animation              447
Musical                394
War                    367
Western                168
IMAX                   153
Film-Noir              133
(no genres listed)      18
Name: count, dtype: int64

In [34]:
movies.explode("genres").genres.value_counts()[:3]

genres
Drama       4365
Comedy      3315
Thriller    1729
Name: count, dtype: int64

In [38]:
a = movies.explode("genres").merge(avg_ratings, left_on = "movieId", right_index = True)
a

      movieId             title     genres  count     mean
0           1  Toy Story (1995)  Adventure    247  3.87247
0           1  Toy Story (1995)  Animation    247  3.87247
0           1  Toy Story (1995)   Children    247  3.87247
0           1  Toy Story (1995)     Comedy    247  3.87247
0           1  Toy Story (1995)    Fantasy    247  3.87247
...       ...               ...        ...    ...      ...
7575    79132  Inception (2010)      Drama    111  4.04955
7575    79132  Inception (2010)    Mystery    111  4.04955
7575    79132  Inception (2010)     Sci-Fi    111  4.04955
7575    79132  Inception (2010)   Thriller    111  4.04955
7575    79132  Inception (2010)       IMAX    111  4.04955

[449 rows x 5 columns]

In [48]:
a['rank'] = a.groupby("genres")["mean"].rank(ascending = False)
a.query('rank <= 3').sort_values(["genres", "mean"], ascending = [True, False])

,movieId,title,genres,count,mean,rank
6916,58559,"Dark Knight, The (2008)",Action,121,4.235537,1.0
953,1196,Star Wars: Episode V - The Empire Strikes Back...,Action,234,4.232906,2.0
232,260,Star Wars: Episode IV - A New Hope (1977),Action,291,4.221649,3.0
953,1196,Star Wars: Episode V - The Empire Strikes Back...,Adventure,234,4.232906,1.0
912,1136,Monty Python and the Holy Grail (1975),Adventure,145,4.224138,2.0
232,260,Star Wars: Episode IV - A New Hope (1977),Adventure,291,4.221649,3.0
3805,4886,"Monsters, Inc. (2001)",Animation,130,3.884615,1.0
0,1,Toy Story (1995),Animation,247,3.872470,2.0
5626,8961,"Incredibles, The (2004)",Animation,126,3.861111,3.0
740,919,"Wizard of Oz, The (1939)",Children,117,3.957265,1.0
3805,4886,"Monsters, Inc. (2001)",Children,130,3.884615,2.0
0,1,Toy Story (1995),Children,247,3.872470,3.0
535,608,Fargo (1996),Comedy,224,4.256696,1.0
266,296,Pulp Fiction (1994),Comedy,324,4.256173,2.0
912,1136,Monty Python and the Holy Grail (1975),Comedy,145,4.224138,3.0
695,858,"Godfather, The (1972)",Crime,200,4.487500,1.0
284,318,"Shawshank Redemption, The (1994)",Crime,311,4.487138,2.0
977,1221,"Godfather: Part II, The (1974)",Crime,135,4.385185,3.0
695,858,"Godfather, The (1972)",Drama,200,4.487500,1.0
284,318,"Shawshank Redemption, The (1994)",Drama,311,4.487138,2.0
977,1221,"Godfather: Part II, The (1974)",Drama,135,4.385185,3.0
912,1136,Monty Python and the Holy Grail (1975),Fantasy,145,4.224138,1.0
954,1197,"Princess Bride, The (1987)",Fantasy,163,4.208589,2.0
3871,4993,"Lord of the Rings: The Fellowship of the Ring,...",Fantasy,200,4.182500,3.0
1288,1617,L.A. Confidential (1997),Film-Noir,125,4.120000,1.0
525,593,"Silence of the Lambs, The (1991)",Horror,304,4.138158,1.0
1012,1258,"Shining, The (1980)",Horror,101,4.029703,2.0
2212,2762,"Sixth Sense, The (1999)",Horror,193,4.018135,3.0
6916,58559,"Dark Knight, The (2008)",IMAX,121,4.235537,1.0
7575,79132,Inception (2010),IMAX,111,4.049550,2.0
129,150,Apollo 13 (1995),IMAX,200,3.902500,3.0
740,919,"Wizard of Oz, The (1939)",Musical,117,3.957265,1.0
328,364,"Lion King, The (1994)",Musical,200,3.777500,2.0
866,1073,Willy Wonka & the Chocolate Factory (1971),Musical,148,3.753378,3.0
48,50,"Usual Suspects, The (1995)",Mystery,201,4.370647,1.0
3367,4226,Memento (2000),Mystery,132,4.227273,2.0
880,1089,Reservoir Dogs (1992),Mystery,132,4.162879,3.0
2288,2858,American Beauty (1999),Romance,220,4.236364,1.0
733,912,Casablanca (1942),Romance,117,4.235043,2.0
954,1197,"Princess Bride, The (1987)",Romance,163,4.208589,3.0
953,1196,Star Wars: Episode V - The Empire Strikes Back...,Sci-Fi,234,4.232906,1.0
232,260,Star Wars: Episode IV - A New Hope (1977),Sci-Fi,291,4.221649,2.0
2062,2571,"Matrix, The (1999)",Sci-Fi,259,4.183398,3.0
48,50,"Usual Suspects, The (1995)",Thriller,201,4.370647,1.0
535,608,Fargo (1996),Thriller,224,4.256696,2.0
266,296,Pulp Fiction (1994),Thriller,324,4.256173,3.0
472,527,Schindler's List (1993),War,244,4.303279,1.0
626,750,Dr. Strangelove or: How I Learned to Stop Worr...,War,105,4.209524,2.0
964,1208,Apocalypse Now (1979),War,112,4.138393,3.0
523,590,Dances with Wolves (1990),Western,202,3.717822,1.0